apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mindwell-backend
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    spec:
      containers:
        - image: gcr.io/GOOGLE_CLOUD_PROJECT/mindwell-backend
          ports:
            - containerPort: 8080
          env:
            - name: GOOGLE_CLOUD_PROJECT
              value: "YOUR_PROJECT_ID"
            - name: ELEVENLABS_API_KEY
              value: "YOUR_API_KEY"
            - name: GOOGLE_CLOUD_LOCATION
              value: "us-central1"
          resources:
            limits:
              memory: 2Gi
              cpu: 1000m
